--https://dbdiagram.io/d/62ee6852c2d9cf52fa5a030f

drop table if exists users cascade;
drop table if exists categories cascade;
drop table if exists events cascade;
drop table if exists requests cascade;
drop table if exists compilations cascade;
drop table if exists categories cascade;
drop table if exists subscriptions cascade;
drop table if exists locations cascade;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name  VARCHAR(30)                             NOT NULL,
    email VARCHAR(50)                             NOT NULL UNIQUE,
    lock  BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    lat NUMERIC(10, 5)                          NOT NULL,
    lon NUMERIC(10, 5)                          NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(128)                            NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    annotation         VARCHAR(2000)                           NOT NULL,
    category_id        BIGINT                                  NOT NULL REFERENCES categories (id),
    created_on         TIMESTAMP DEFAULT NOW(),
    description        VARCHAR(7000)                           NOT NULL,
    event_date         TIMESTAMP                               NOT NULL,
    initiator_id       BIGINT                                  NOT NULL REFERENCES users (id),
    location_id        BIGINT                                  NOT NULL REFERENCES locations (id),
    paid               BOOLEAN   DEFAULT FALSE,
    participant_limit  BIGINT                                  NOT NULL,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN   DEFAULT FALSE,
    state              VARCHAR(50),
    title              VARCHAR(120)                            NOT NULL,
    views              BIGINT                                  NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    title  VARCHAR(500)                            NOT NULL,
    pinned BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    event_id       BIGINT                                  NOT NULL REFERENCES events (id),
    compilation_id BIGINT                                  NOT NULL REFERENCES compilations (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    event_id     BIGINT                                  NOT NULL REFERENCES events (id),
    requester_id BIGINT                                  NOT NULL REFERENCES users (id),
    state        VARCHAR(50)                             NOT NULL,
    created      TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS subscriptions
(
    user_id         BIGINT NOT NULL REFERENCES users (id),
    subscription_id BIGINT NOT NULL REFERENCES users (id),
    blacklist       BOOLEAN DEFAULT FALSE,
    PRIMARY key (user_id, subscription_id)
)