drop table if exists endpointhit cascade;

CREATE TABLE IF NOT EXISTS endpointhit (
    hit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app VARCHAR(30) NOT NULL,
    uri VARCHAR(2048) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_hit PRIMARY KEY (hit_id)
);
